passwordHash: ENC[AES256_GCM,data:RM0+n7FAMvVgHY7OgfOFBHnJRPoE3B7UUqn/qezoYGpDdGRCwGcgsRvxk1t12riCsMx5302j0MChbV9N57y/bZy+Gum/3bOzTQ==,iv:zWuuDwZGmHpuDjr1+Vs71T0sjN0pdvrC4CaO7Y14sQk=,tag:7QFZIEIqyT3rtVnKwb/5JQ==,type:str]
sops:
    age:
        - recipient: age1azews403uk79n9zrk2rvpvtawvdwawehxcf75zfk5jt9djcan9pq7lrt32
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOHNCeE84Mkk4RXRRTHpC
            MXVOVzVFOUVtMVQrR1AzVlNNRk5XNGVSRVZzCm1Ea04zRDlmaVozZjNVa1A5ZXR4
            Y0ZuMFM1UlBFWTRJSGZpUDJFVkxxMVUKLS0tIHkzWnBtUWx0UUFzRU13eUVRQktk
            b1YvNXFWWlQrekZycXlGWUx1L1FHUG8KLK8NBWXfGwDeR0PBxeN28g1x8OsK2kBZ
            JyZJS4G7+Jm/a3v1v7KxdzrDuJKpKQq0Urf4ai69DdQLkSKT2k7nZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T21:32:16Z"
    mac: ENC[AES256_GCM,data:UkJOVSBJHdztH6kT3rdFOAwReh3fbAbWKTSBUwghJKDd1JZp3dphxFr9Quc71hWIU8wbMRoOcy3zaIEIJTvR3QUBvGPygpd1P1D6/47Kg0mXdewEwQNXnda4HG+ALlgYlqQdlb6XRP1e2MFrwOgUpv8VDozuC9hbU3sp7npjuT4=,iv:iYr1z5i9huIE7ISCVzrtsm2ayc2FlejVZq849DLGg8Y=,tag:bqOVXX6fH//j8KwjLEuFNw==,type:str]
    pgp:
        - created_at: "2025-12-21T19:27:35Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DiGOBemEMayYSAQdAlg0SFp2pbS8291UgTtW7XKPzMA0U9+uHFCTMD4GsLGAw
            8H1r3KdZVNeCpNa7Ow9JaX5UNa/gqQM2E7TTyL/NyJIXkU6G7J6GzAL5CXq9DX5M
            0l4BgLp4AYbRbMSVA9jVoVcNwZ4IvyP1wn3+0UOE6AXMOBwKlUPSkS44XAy6+5Yg
            6SV+OaPDttkbwihdJmMixOZ5t2PYrWUGfgV+hduhuNqSDIGKDpASgbVHPHZdDKaA
            =W1Cm
            -----END PGP MESSAGE-----
          fp: 38B60A41D64140C18F4594E18863817A610C6B26!
    unencrypted_suffix: _unencrypted
    version: 3.11.0
