hfToken: ENC[AES256_GCM,data:f4sHlMTNCfCLaGlfYLBrzLZFY8UJZQC2E+0F53zZwneRPiVB7w==,iv:x6Tv7ebTs8oiyPmvFA35C7T7+1QN6PQ1xpQWsKVAtUU=,tag:4qi5fR8cSQqAJl0S5ldOPg==,type:str]
civitToken: ENC[AES256_GCM,data:zuLvi8PsdB1fwv3af0sCL7SHCEebUsxvoU+YpTzKqJI=,iv:nY45n0s3L6dkKvGAzzUgNzL7ZvqwSTzL8+cD2lmW5+8=,tag:Yu+RMYGsy0lBraPY/0N7Jg==,type:str]
sops:
    age:
        - recipient: age1azews403uk79n9zrk2rvpvtawvdwawehxcf75zfk5jt9djcan9pq7lrt32
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dEFVSythS3cwODZ5Vjlx
            NHhra0dtWUFFUTdpRlNEMi9zd3l3Z3pFK2pJCi9ZWUYwa2FqYnBCcnB0Yzd6ejJs
            WC9tQlkvci9KOVRLUUhhaXpFY1R4Q0UKLS0tIHBGcXBtT1NXeFhIWUJWaUUxZTY5
            NkcyY1BBdHNZU3hwbHV4ZkRFWG5BRlEK+ALjpjEVqXeTdb83+WRLuuSgckaKZ68i
            a+L9/NcjajPE0Atm1LGeMnKiYxjZKYypAdAJs78SGM3l8SXNK6dR7g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vgzm44xe935uq2769hr2xcxvqzhz0rlzwsl9p03lkwz7t4dqy32q3azzkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5ZkpRbSs1dGtZVnREQ2R1
            a2p4U21SMElLRE5qMlhIMFdZZW9KVTU4OFRBCmZMU1VVVndMSXAzc0pTZ3VSU25F
            WEFxTkVtRTlWVVBIRmJ1WU9QbXVyVGMKLS0tIEtNNnNnY0hUYVd1RVRUNFMrMi94
            eTRDZ0ZNOTB5amllYjlQMTlTSlZDS1kKg6tyRjwl6ttSIcVaeQO9OwS0E46ZJ5Ra
            s0ORwH/HraJ0Gw+/Y5UoNg64a7DKyAYWasYBjtGFucnkoE++2FL4kQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T21:51:29Z"
    mac: ENC[AES256_GCM,data:UcXjJ2rJKzbCd0TPAf0vfb7PNr98g77lzdYeBysNcIkDdDdV9n3rdbCz65GtTEZ75SninG729lRX2XtbVviGGefE47QRozxUpChrrZzBAngeV46MBj9mNQtCouds9wG0fdmNt/h7hzzalyyY/H5I29VyTZu65L7WBqQp97Lj3tA=,iv:19cyaEa6m6jGvyuw1jbwBJwWX0V+pRsua2uke8FS54Q=,tag:0MXbv0jnb5YSDBAxYGR51A==,type:str]
    pgp:
        - created_at: "2025-12-22T21:50:44Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DiGOBemEMayYSAQdAOTN/CjLwWKSqm4cJY+2GkM6/4y2C5yFNd6AM+wUG9m4w
            cxMCjW3hptKC+3adv387HWOrwlMaSiiEIZ7AwyFzRZgzSXXBJiJRK7XNUhsP/GT/
            0lEB0bPfdV9vbv1fthmB09h/aCp7EfO+TL6Fny+8QHTUBSCxDqzDymv7JHWiiwga
            YA0JwWI4/HWvlyQhKP+QSARIJm1VTKKThcn+TL+dhBtew3M=
            =PiNp
            -----END PGP MESSAGE-----
          fp: 38B60A41D64140C18F4594E18863817A610C6B26!
    unencrypted_suffix: _unencrypted
    version: 3.11.0
