passwordHash: ENC[AES256_GCM,data:qkbCvkCbkbsw24kJKRshs9l2gCkeCgNQp/In0O8J7AOZcQugNK87qj4qHRow2+doVtjn3iRTcY8DPqtZ+pZu0YSr8GZTr5xb4Q==,iv:pHD4HJqAdWYAw/x58FD2EuRXpQ++m2kqLSHJZoI6c+A=,tag:m7zsVrmhEJVdGtgAnIjI8A==,type:str]
sops:
    age:
        - recipient: age1vgzm44xe935uq2769hr2xcxvqzhz0rlzwsl9p03lkwz7t4dqy32q3azzkz
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Qm13L2JHcWkzb2VaY3Vj
            VmhLK2w1bGVDQWovME5ocWUxV014TUoyNUR3Cmh2NFkwR1BnWUhOOS9qVkZsMFFM
            TEFjd0RQcFlGUmlTQ1ljcExrcVZpYXMKLS0tIFRPSVYwWW9wRzRsZ1hCbWEyYmZ6
            YjlocGFYejNjcVZGN09KSG90QzhkYVkKTMsyOiSUEyCk0/vZFQIh1+irsqAiy2fa
            MhlAqB7XiD1ul8OIdEFRSphZbZNXwrw4Rkh21HnT/KYw7ZtT1iFlKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-22T21:36:10Z"
    mac: ENC[AES256_GCM,data:hxCOZDZkkoTftunTYsgs0PQ9QmbCvXRG0HOhUEkwF7o7qdSuqV/cu8mxDhPjl/9lJcCFcbk862ppwLQmT03RulvOsKhcyJeJgiLXpB0eQSVGiIoa2m9g8zZVgI7b3Q2SIfz6vLn5lJOmDL8iw0WWdFs60WF734Jx9v+QS4rqD0U=,iv:/gQa45+wNHn46KNi7Xbg+Dbg4k33hh9/NHbboyxZbfU=,tag:MeXtCZspAtPIP/R+gsm6Lg==,type:str]
    pgp:
        - created_at: "2025-12-22T21:20:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DiGOBemEMayYSAQdAYap0rAkOeDaWNTu8Yp9qx1gj35/bQwAHCvZSzSgYhDAw
            dpybVsq+TMSXe4lvsQ8spljvWn7gK08odZ811Vww/qhADV+xOM4k80tpZ32nZhwN
            0l4B+rllyoh1RsiFYhMad+QuUyZRCUAmNuHdk6Iyl8knPtM4JlNGBqjLq68qwmmq
            aGvGoFBDbt5JZclhKTxJjwoahoCIe34iNdT8opHy+ZLzB9MylwgeUisO3+chhiQ8
            =hqgw
            -----END PGP MESSAGE-----
          fp: 38B60A41D64140C18F4594E18863817A610C6B26!
    unencrypted_suffix: _unencrypted
    version: 3.11.0
